---
- name: Apply ssh_hardening role on Web App Server
  - name: Set PermitRootLogin to no
    lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^PermitRootLogin'
      line: 'PermitRootLogin no'
    notify: restart ssh

  - name: Disable password authentication
    lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^PasswordAuthentication'
      line: 'PasswordAuthentication no'
    notify: restart ssh

  - name: Set SSH protocol to 2
    lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^Protocol'
      line: 'Protocol 2'
    notify: restart ssh

  - name: Allow only specific users to SSH
    lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^AllowUsers'
      line: 'AllowUsers username1 username2'
    notify: restart ssh
