---
- name: Create Database User
  become: true
  postgresql_user:
    db: my_database
    name: postgres
    password: anonym
    state: present
    login_host: localhost

- name: Grant necessary privileges to the database user
  become: true
  postgresql_privs:
    db: my_database
    user: postgres
    priv: ALL
    state: present
    login_host: localhost
